const truthOrDare = {
    truths: [
        "Do you sing in the shower?",
        "What’s your biggest fear?",
        "What’s the weirdest dream you’ve had?",
        "Who do you think is the best-looking person in the room?",
        "Have you ever had a crush on someone in this room?",
        "What’s the last lie you told?",
        "What’s the most embarrassing thing you’ve done?",
        "Have you ever pretended to be sick to get out of something?",
        "What’s the worst gift you’ve ever received?",
        "Who was your first crush?",
        "What’s your favorite color?",
        "Do you like pineapple on pizza?",
        "Have you ever stolen something?",
        "Who is your best friend?",
        "What’s your favorite movie?",
        "What’s your dream job?",
        "Do you believe in love at first sight?",
        "What’s the craziest thing you’ve ever done for fun?",
        "Do you have any hidden talents?",
        "Do you believe in ghosts?",
        "What’s the worst thing you’ve ever said to someone?",
        "What’s the best advice you’ve ever received?",
        "Who would you call if you needed help?",
        "Do you like scary movies?",
        "What’s the most ridiculous thing you’ve believed as a child?",
        "If you could switch lives with someone for a day, who would it be?",
        "What’s your favorite type of music?",
        "What’s your favorite hobby?",
        "If you could live anywhere in the world, where would it be?",
        "What’s your biggest pet peeve?",
        "What’s the funniest thing you’ve ever seen someone do?",
        "What’s your idea of a perfect day?",
        "What’s your favorite food?",
        "What’s your go-to comfort food?",
        "Have you ever had a secret crush on a teacher?",
        "Have you ever skipped school?",
        "What’s the most embarrassing thing you’ve done in front of a crush?",
        "What’s the longest you’ve ever gone without sleep?",
        "What’s the silliest thing you believed as a child?",
        "Do you like doing karaoke?",
        "Have you ever had a crush on a fictional character?",
        "What’s your guilty pleasure?",
        "If you could meet anyone in the world, dead or alive, who would it be?",
        "What’s the most random thing you own?",
        "What’s your dream vacation?",
        "What’s the most awkward thing that’s happened to you recently?",
        "What’s one thing you want to accomplish in the next year?",
        "What was the best birthday party you ever had?",
        "If you could have any animal as a pet, what would it be?",
        "What’s the last book you read?",
        "What’s your biggest fear?",
        "If you could talk to one animal, which would it be?",
        "What’s your favorite season of the year?",
        "What’s your least favorite chore?",
        "What’s your favorite holiday?",
        "What’s your worst habit?",
        "What’s the worst haircut you’ve ever had?",
        "What’s your favorite thing to do on weekends?",
        "What’s the best concert you’ve ever been to?",
        "Do you like to travel?",
        "What’s the most embarrassing thing you’ve done in public?",
        "Who’s your favorite family member?",
        "What’s the most unusual thing you’ve eaten?",
        "What’s something you’ve always wanted to try?",
        "Do you prefer dogs or cats?",
        "If you could be a famous person for a day, who would you be?",
        "Do you believe in aliens?",
        "What’s your favorite TV show?",
        "What’s the best compliment you’ve ever received?",
        "What’s your favorite kind of weather?",
        "What’s the best thing about being your age?",
        "What’s one skill you wish you had?",
        "What’s the best compliment you could receive?",
        "What’s the longest road trip you’ve ever been on?",
        "What’s the best gift you’ve ever received?",
        "If you could be famous for one thing, what would it be?",
        "What’s the most unusual thing you’ve done for fun?",
        "Do you enjoy playing board games?",
        "What’s the last thing you Googled?",
        "What’s the best meal you’ve ever had?",
        "If you could visit any country, where would you go?",
        "What’s the best movie you’ve seen this year?",
        "What’s your most embarrassing social media post?",
        "What’s the most ridiculous thing you’ve done while drunk?",
        "What’s the worst date you’ve ever been on?",
        "Have you ever had a crush on a teacher?",
        "What’s the longest time you’ve gone without talking to your best friend?",
        "What’s the most embarrassing thing you’ve done in front of your parents?",
        "What’s something you’ve done that you regret?",
        "What’s something you’ve never told anyone?",
  "If you could switch lives with anyone for a day, who would it be and why?",
  "What’s the most embarrassing thing you’ve ever done in public?",
  "Have you ever broken someone’s heart? What happened?",
  "What’s a secret talent that no one knows about?",
  "If you could be famous for one thing, what would it be?",
  "What’s the most awkward thing that’s ever happened to you on a date?",
  "Have you ever lied to get out of a situation? What was the lie?",
  "What’s the most trouble you’ve ever gotten into at school or work?",
  "What’s a habit you’ve had for years that you can’t shake?",
  "If you could ask anyone one question and get the truth, who would you ask and what would the question be?"

    ],
    dares: [
        "Dance with no music for 1 minute.",
        "Pretend to be a waiter/waitress and take drink orders from everyone.",
        "Do 20 push-ups.",
        "Act like a monkey until it’s your turn again.",
        "Post an embarrassing photo on your social media.",
        "Imitate a celebrity of the group’s choice.",
        "Let someone write a word on your forehead with a marker.",
        "Eat a spoonful of hot sauce.",
        "Speak in an accent (British, French, etc.) until it’s your turn again.",
        "Let someone else redo your hairstyle.",
        "Do your best impression of someone in the room.",
        "Run around the outside of the house three times.",
        "Wear socks on your hands for the next 10 minutes.",
        "Do an impression of a baby being born.",
        "Post a silly video on social media.",
        "Let someone draw on your face with a pen.",
        "Talk in a high-pitched voice until your next turn.",
        "Pretend to be a waiter/waitress and take everyone’s food orders.",
        "Send a message to your crush or significant other with just emojis.",
        "Imitate a baby until it’s your turn again.",
        "Try to lick your elbow.",
        "Post a funny status on your social media account.",
        "Do your best chicken dance outside on the lawn.",
        "Run around the yard screaming your name.",
        "Call a random number and sing “Happy Birthday” to them.",
        "Let someone tickle you for 30 seconds.",
        "Do an impression of a baby crying.",
        "Wear socks on your hands for the next 5 minutes.",
        "Talk like a pirate until it’s your turn again.",
        "Make up a rap and perform it.",
        "Do 50 sit-ups.",
        "Try to juggle 3 items.",
        "Do your best impression of a baby being born.",
        "Imitate a baby until your next turn.",
        "Call a friend and sing “I Will Survive” by Gloria Gaynor.",
        "Do a cartwheel.",
        "Send a text to your ex saying, “I miss you.”",
        "Let someone else draw on your face with lipstick.",
        "Talk in a high-pitched voice until your next turn.",
        "Pretend to be a waiter/waitress and take everyone’s orders.",
        "Do your best impression of an animal until your next turn.",
        "Dance like no one is watching for 1 minute.",
        "Run around the house 3 times.",
        "Let someone else change your Facebook status.",
        "Pretend to be a statue for 2 minutes.",
        "Pretend you’re a waiter/waitress and take everyone’s food orders.",
        "Do 20 squats.",
        "Let someone post an embarrassing photo of you.",
        "Send a message to your crush saying, “I think you’re awesome!”",
        "Let someone else control your social media for the next 10 minutes.",
        "Do your best impression of a baby crying.",
        "Call your mom and tell her a joke.",
        "Let someone else choose a song for you to sing.",
        "Post something embarrassing on social media.",
        "Do your best impression of a famous person.",
        "Wear socks on your hands for the next 10 minutes.",
        "Let someone draw a mustache on your face.",
        "Do 25 jumping jacks.",
        "Talk in a robot voice for the next 5 minutes.",
        "Send a text to your crush saying, “I think you’re amazing!”",
        "Do your best impression of a chicken until it’s your turn again.",
        "Imitate a baby crying until your next turn.",
        "Dance with no music for 1 minute.",
        "Let someone do your makeup however they like.",
        "Call a random number and tell them a joke.",
        "Pretend you are an animal of the group’s choice for 1 minute.",
        "Eat a spicy food of the group’s choice.",
        "Do your best impression of a famous singer.",
        "Pretend to be a statue for 2 minutes.",
        "Do your best impression of a celebrity until someone guesses who it is.",
  "Send a random emoji to the last person you texted.",
  "Let someone write a word on your forehead with a marker.",
  "Call a random contact and sing 'Happy Birthday' to them.",
  "Do 20 push-ups in a row.",
  "Dance with no music for 1 minute.",
  "Try to lick your elbow.",
  "Walk on your knees for the next 5 minutes.",
  "Try to juggle 3 objects.",
  "Do 10 jumping jacks and shout a random animal sound.",
  "Talk in an accent (e.g., British, Australian) for the next 5 minutes.",
  "Post a silly photo on your social media without any explanation.",
  "Share the most embarrassing story from your childhood.",
  "Let someone draw a mustache on your face with a washable marker.",
  "Walk backwards for the next 3 minutes.",
  "Try to touch your toes with your tongue.",
  "Let the person to your left take a funny selfie of you.",
  "Do your best impression of a robot.",
  "Wear socks on your hands for the next 10 minutes.",
  "Do a cartwheel.",
  "Pretend to be a waiter/waitress and take an order from everyone in the room.",
  "Sing the chorus of a song as loudly as possible.",
  "Post a 'random thought' on your social media.",
  "Try to whistle and hum at the same time.",
  "Hold your breath for 15 seconds.",
  "Pretend you’re a news anchor and give a report on a random topic.",
  "Make a funny face and hold it for 1 minute.",
  "Try to balance a spoon on your nose for 30 seconds.",
  "Call a friend and tell them a funny joke.",
  "Do your best dance move to a random song.",
  "Act like an animal until someone guesses which one you are."
]
};

const truthbtn = document.getElementById("truth")
const darebtn = document.getElementById("dare")
const content = document.getElementById("content")
const nextPlayer = document.getElementById("nextplayer")
const player = document.getElementById("player")

function funTruth(){
    let index = Math.floor(Math.random()*truthOrDare.truths.length)
    content.textContent=truthOrDare.truths[index]
    content.style.color="#28a745"
    console.log(truthOrDare.truths.length)
}
function funDare(){
    let index = Math.floor(Math.random()*truthOrDare.dares.length)
    content.textContent=truthOrDare.dares[index]
    content.style.color="#dc3545"
    
}
function funNextPlayer(){
    player.textContent === "Player 1" ? (player.textContent="Player 2") : (player.textContent="Player 1")
    content.textContent="Choose"
    content.style.color="black"
}

truthbtn.addEventListener("click",funTruth)
darebtn.addEventListener("click",funDare)
nextPlayer.addEventListener("click",funNextPlayer)


